### PR TITLE
Animation Glitch Fixed

### LINKED ISSUE #158: using WASD without letting the click to move reach its target location causes the player animation to break

### LINKED ISSUE #159: WASD movement and click to move movement are two different speeds
these should be the same speed for consistency

### LINKED ISSUE #168: Increase avoidance radius for NPCs

### LINKED ISSUE #171: Change numeric score to adjectives

### LINKED ISSUE #173: Make journal less redundant

### LINKED ISSUE #182: How to Play Exit Not Working
**Describe the bug**
In the initial How to Play screen (not the journal one) you cannot click on the X to exit.

### PR DESCRIPTION
**Pull request by brimstonetrader**

### CODE REVIEW

**Comment by jonesamelia** [comment]
The number of days left is not decreasing after travelling. testJournal.testAddToJournal is also giving an index out of range error.

**Comment by jonesamelia** [comment]
Screenshot 2024-05-07 104000
The journal did this after the quakes.

**Comment by brimstonetrader** [comment]
This should be fixed now, I believe it was because the font size was too big for some orderings.

**Comment by jonesamelia** [comment]
It is still overlapping a bit because some of the texts are longer than their box. I think turning auto size back on for each textbox would fix it?
Days left also still stays at 10.

**Comment by brimstonetrader** [comment]
Sorry about that, I guess I hadn't pushed my title screen changes. They're in now.

**Pull request merged**
