### PR TITLE
Player Movement via Clicking Screen

### LINKED ISSUE #90: npcs shouldnt walk through houses

### LINKED ISSUE #104: people are jesus walking in the river scene

### LINKED ISSUE #109: Change NPC pathfinding to A* with collision recognition
Should fix Jesus walking

### LINKED ISSUE #117: Make people continue wandering after you speak to them

### LINKED ISSUE #118: Click point on screen to walk

### LINKED ISSUE #119: Click on character to speak to them

### LINKED ISSUE #122: Merge both interaction scripts

### LINKED ISSUE #127: Add trees and collider-y stuff around perimeter of river
weird just bumping up against nothing

### LINKED ISSUE #130: Correct "St.LouisPostQuakes"  typo in GameManager that messes with scene flow

### LINKED ISSUE #131: Specific Lines of Feedback based on what's chosen, not what's heard

### PR DESCRIPTION
**Pull request by brimstonetrader**

### CODE REVIEW

**Comment by keyszl** [comment]
One of the NPCs in the madrid scene is missing the movement script

**Comment by keyszl** [comment]
you shouldn't move when you click in the journal/exit out of the journal, etc. Also moves the character if they click to move through dialogue.

Camera zoom is broken, didn't work for me when clicking to chat

Walking animation seems a bit long (might be on my end), keeps doing the animation for about an extra second once the character is stopped in place

Some NPCs still walked through houses for me in the madrid and st louis, pre-quake and post-quake

NPC avoid collision should include avoiding not only when player is in conversation, but when player has stopped another NPC due to proximity, I got stuck in between two NPCs in the river and couldn't click out of it (WASD did work though)

people are still slightly jesus walking in the river scene

**Comment by brimstonetrader** [comment]
I fixed the first two problems, and removed two of the issues you said are still causing problems. I don't believe this pull request is causing new issues now.

**Comment by keyszl** [comment]
After talking to an non-important NPC the camera zoomed in and then never zoomed out for me

**Comment by brimstonetrader** [comment]
Should be fixed now

**Comment by jonesamelia** [comment]
The player seems to move at half the speed when clicking.

**Comment by brimstonetrader** [comment]
Should be fixed now

**Pull request merged**
