### PR TITLE
Dynamic Article Generation

### PR DESCRIPTION
**Pull request by brimstonetrader**

### CODE REVIEW

**Comment by keyszl** [comment]
the NPCs dont stop anymore when you try to talk to them on this branch

**Comment by brimstonetrader** [comment]
Was it in RiverPreQuake? All my NPCs stopped in every town but that one.

**Comment by keyszl** [comment]
it was madrid pre-quake

**Comment by brimstonetrader** [comment]
I couldn't find any NPC that didn't stop when I talked to them there. I merged your changes in, that might fix the problem on your end.

**Comment by keyszl** [comment]
works for me! I had the wrong branch of yours checked out, going to merge this

**Pull request merged**
